### ISSUE TITLE
Filter by int doesn't work

### ISSUE THREAD

**Issue by igorsantos07** [FlowCommunications/JSONPath#12]
I'm not exactly sure if this is a bug or one of the shortcomings of the filter syntax described on the readme. Would be great if this worked, but if it's not possible, document the issue so others do not stumble upon :)

I'm trying to filter entries by a single integer value, but that triggers a "malformed filter query" error.
This is the filter I'm using: `$.results[?(@.id = 1)]`. To have it working, I simply had to quote the ID, like `$.eligible_billables[?(@.id = "1")]`.

**Comment by stephenfrank** [comment]
Hi Igor,

Yep, that was definitely a bug... unintentionally the regular expression was only working with 2 or more characters!
