### ISSUE TITLE
JSONPathLexer breaks with given expression $

### ISSUE THREAD

**Issue by simonberger** [FlowCommunications/JSONPath#27]
JSONPathLexer crashes on [line 46](https://github.com/FlowCommunications/JSONPath/blob/master/src/Flow/JSONPath/JSONPathLexer.php#L46) with a given expression of just '$'.
It is an out of bound check on an empty string. The error message is: "Uninitialized string offset: 0"
While this worked on PHP 5.x it does not anymore with PHP 7.2

**Comment by lenrsmith** [comment]
Is there any word on when/if the above PR will be merged? We are facing the same problem on a PHP 7.2 upgrade.

**Comment by simonberger** [comment]
I would like to see a fix for this as well. You can easily work around this by calling it with an empty  expression string (or null if you have to) as the lexer just removes the $ anyway. But in some third party package uses this may simply bet not possible.

@stephenfrank Can this be fixed or do you not maintain this package anymore ?
