### ISSUE TITLE
Class 'JSONPath' not found

### ISSUE THREAD

**Issue by zQueal** [FlowCommunications/JSONPath#3]
After cloning the repository and running `composer update`, I include the `vendor/autoload.php` file into a test `index.php` file to test the README example:

``` php
<?php

require('vendor/autoload.php');

$data = ['people' => [['name' => 'Joe'], ['name' => 'Jane'], ['name' => 'John']]];
$result = (new JSONPath($data))->find('$.people.*.name');

```

Result: `PHP Fatal error:  Class 'JSONPath' not found in index.php on line 6`

Any ideas, here?

**Comment by theDanielJLewis** [comment]
I know this is over 5 years old, but I need the solution, too. What was the problem, @zQueal?
