### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by necrosisoff** [FlowCommunications/JSONPath#4]
Call to undefined method Flow\JSONPath\AccessHelper::collectionKeys() in /var/www/vendor/flow/jsonpath/src/Flow/JSONPath/JSONPath.php on line 67

**Comment by stephenfrank** [comment]
Whoops... a bit of a test coverage issue there for the first() and last(). Thanks for letting me know. I've fixed the issue in 0.2.3 and added a test at least.
