### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kevcooper** [FlowCommunications/JSONPath#47]
Any chance we could get a new release tagged and ideally pushed to packagist? Might be an opportunity to jump to 1.0.0 since there were breaking changes introduced in the recent series of commits.

**Comment by generalredneck** [comment]
for any who need to use master but are afraid of setting to a branch. you can always pin your requirements to the latest commit by doing something like

```
{
    "require": {
        "flow/jsonpath": "dev-master#abbc17d1696bbda16698e82775fb506cc5b6b5e8"
    }
}
```

**Comment by stephenfrank** [comment]
Hey, apologies for being AWOL on this project. I have pushed up the tag for 0.5.0!

**Comment by kevcooper** [comment]
Thanks!

**Comment by kevcooper** [comment]
Any chance we could get a packagist update too? 😃

**Comment by stephenfrank** [comment]
Done. Not sure what happened there... it's supposed to update via webhook but maybe it didn't fire off the required events.

**Comment by kevcooper** [comment]
Thank you!!
