### ISSUE TITLE
Doesn't not work with certain strings which contain slashes

### ISSUE THREAD

**Issue by oparoz** [FlowCommunications/JSONPath#6]
Using the following JSON example
```
{
	"features": [],
	"mediatypes": {
		"image/png": "/core/img/filetypes/image.png",
		"image/jpeg": "/core/img/filetypes/image.png",
		"image/gif": "/core/img/filetypes/image.png",
		"application/postscript": "/core/img/filetypes/image-vector.png"
	}
}
```

with the [online tester](https://jsonpath.curiousconcept.com)

Query:

* `$['mediatypes']['image/png']`
* `$.mediatypes.image/png`

Result with `FlowCommunications/JSONPath` 0.3: 

* empty
* error

Result with original JSONPath 0.8.3

* "\/core\/img\/filetypes\/image.png"
* "\/core\/img\/filetypes\/image.png"

**Comment by stephenfrank** [comment]
Hi Olivier,

I can confirm that the online checker doesn't seem to return the right result however the library is working (I've added a test and it's returning correctly).

```
    public function testSlashesInIndex()
    {
        $result = (new JSONPath($this->exampleDataWithSlashes()))->find("$['mediatypes']['image/png']");
        $this->assertEquals(
            [
                "/core/img/filetypes/image.png",
            ],
            $result->data()
        );
    }
```

I have to assume that there is an encoding/decoding issue that is happening with the online tester.

I've tweeted them and hopefully they could weigh in.
