### ISSUE TITLE
offsetUnset doesn't work properly

### ISSUE THREAD

**Issue by lucacerretani** [FlowCommunications/JSONPath#7]
In the following example the offsetUnset doesn't work properly.
The element is removed from the $route but still exists in $jsonIterator.

Can you please check?
```php
$data = array(
    "route" => array(
        array("name" => "A", "type" => "type of A"),
        array("name" => "B", "type" => "type of B")
    )
);
$data = json_encode($data);

$jsonIterator = new Flow\JSONPath\JSONPath(json_decode($data));

$route = $jsonIterator->offsetGet('route');

// var_dump($route);

$route->offsetUnset(0);

// var_dump($route);

var_dump($jsonIterator);
```

**Comment by stephenfrank** [comment]
Hi Luca,

I think you've made a mistake here with the `vardump`:

```
- var_dump($jsonIterator);
+ var_dump($route);
```

gives me

```
class Flow\JSONPath\JSONPath#25 (2) {
  protected $data =>
  array(1) {
    [1] =>
    class stdClass#24 (2) {
      public $name =>
      string(1) "B"
      public $type =>
      string(9) "type of B"
    }
  }
  protected $options =>
  int(0)
}
```

**Comment by lucacerretani** [comment]
Hi Stephen,

Thank you for your reply and for the test that helps me to explain the problem.

The assertion that I expect to success is in the following test:

```php
    public function testOffsetUnset()
    {
        $data = array(
            "route" => array(
                array("name" => "A", "type" => "type of A"),
                array("name" => "B", "type" => "type of B")
            )
        );
        $data = json_encode($data);

        $jsonIterator = new JSONPath(json_decode($data));

        /** @var JSONPath $route */
        $route = $jsonIterator->offsetGet('route');

        $route->offsetUnset(0);

        $first = $route->first();

        $this->assertEquals("B", $first['name']);

        $this->assertEquals("B", $jsonIterator->route->first()['name']);
    }
```

Luca.

**Comment by flowcomm** [comment]
Oh okay, I see what you mean.

I did start an experimental version that allows for modification of the
underlying data which requires that everything be passed as reference and
function calls to return references. This *might* work for your use case
but I haven't tested it.

I'll see if I can push this as a branch but I haven't had time to look at
it or test it as much as I'd like.

No ETA from me unfortunately.


On 12 October 2015 at 17:59, lucacerretani <notifications@github.com> wrote:

> Hi Stephen,
>
> Thank you for your reply and for the test that helps me to explain the
> problem.
>
> The assertion that I expect to success is in the following test:
>
>     public function testOffsetUnset()    {        $data = array(            "route" => array(                array("name" => "A", "type" => "type of A"),                array("name" => "B", "type" => "type of B")            )        );        $data = json_encode($data);        $jsonIterator = new JSONPath(json_decode($data));        /** @var JSONPath $route */        $route = $jsonIterator->offsetGet('route');        $route->offsetUnset(0);        $first = $route->first();        $this->assertEquals("B", $first['name']);        $this->assertEquals("B", $jsonIterator->route->first()['name']);    }
>
> Luca.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FlowCommunications/JSONPath/issues/7#issuecomment-147446150>
> .
>



-- 


Stephen Frank
Web Developer



TEL 27(0)114404841

FAX 27(0)866309187

CELL 27(0)832580576

EMAIL stephen@flowsa.com

SKYPE stephenfrank_za
www.flowsa.com
