### ISSUE TITLE
!= filter doesn't work

### ISSUE THREAD

**Issue by johncrenshaw** [FlowCommunications/JSONPath#9]
QueryMatchFilter::MATCH_QUERY_OPERATORS is missing cases for != and !==, so even though the filter logic is present, filters using != fail with a malformed filter error

To fix, make the following change in QueryMatchFilter::MATCH_QUERY_OPERATORS

```
    const MATCH_QUERY_OPERATORS = '
    @(\.(?<key>\w+)|\[["\'](?<keySquare>.*?)["\']\])
    (\s*(?<operator>==|=|!==|!=|>|<)\s*(?<comparisonValue>\S.+))?
    ';
```

**Comment by stephenfrank** [comment]
Hi johncrenshaw

Thanks for picking that up. I'd completely missed that.

This commit 0.3.2 should fix that...
https://github.com/FlowCommunications/JSONPath/commit/4143352f15700f623ac35f196aca4519de602db3
